### ISSUE TITLE
Habitat-sim dependency: python 3.7 vs python 3.9

### ISSUE THREAD

**Issue by e-zorzi** [aimagelab/pin#2]
Hi thanks,
Thanks for releasing this repo. 

I want to install _pin_, but I have problems compiling the shipped habitat-sim (version 0.2.3), so I am trying to install it via _conda_.
However, the main problem is that the checked versions of habitat-sim and habitat-lab require python 3.7, whereas _pin_ requires python 3.9. 

My question is: can I just use habitat-sim (and -lab) 0.2.4? This way, python versions would not be mismatched.

I did install habitat-sim 0.2.4 just fine - however, while running the eval script, I encountered this error:

```
TypeError: __init__() got an unexpected keyword argument 'distractors'"
```

referring to ```NavigationEpisode(**episode) ``` (from the function ```from_json``` from the file ```habitat/datasets/pointnav/pointnav_dataset.py```

Downgrading to python3.7 is not possible as some required packages are not compatible with it (e.g. transformers)
Can you test whether it works with habitat 0.2.4, and the problem lies elsewhere, or is habitat 0.2.3 mandatory?

Thanks for the support.
Cheers,
Edoardo
